{{- if .Values.webhook.enable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ .Release.Name }}-webhook-svc.{{ .Release.Namespace }}.svc
  - {{ .Release.Name }}-webhook-svc.{{ .Release.Namespace }}.svc.cluster.local
  - { .Release.Name}.{ .Release.Namespace}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Release.Name }}
  secretName: {{ .Release.Name }}-cert
{{- end }}
